// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/get-switch-status.ts
import { createClient } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_switch_status_default = defineTool({
  name: "get_switch_status",
  title: "Get dead man's switch status",
  description: "Return the signed-in user's dead man's switch status: whether it is active, when the next check-in is due, last check-in time, grace period state, and whether the switch has been triggered.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("user_settings").select(
      "is_active, deadline_mode, check_in_frequency, last_check_in, next_check_in_due, grace_period_active, grace_period_end, grace_period_hours, switch_triggered, switch_triggered_at, custom_deadline"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: "No switch configured yet." }],
        structuredContent: { configured: false }
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { configured: true, status: data }
    };
  }
});

// src/lib/mcp/tools/perform-check-in.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var perform_check_in_default = defineTool2({
  name: "perform_check_in",
  title: "Check in (reset the switch)",
  description: "Record a check-in for the signed-in user. This resets the dead man's switch countdown, cancels any active grace period, and logs the check-in in history. Use when the user tells their assistant they are still alive/well and want to postpone the switch.",
  inputSchema: {},
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser2(ctx);
    const userId = ctx.getUserId();
    const now = /* @__PURE__ */ new Date();
    const { data: settings, error: readErr } = await supabase.from("user_settings").select("check_in_frequency, deadline_mode, grace_period_hours").eq("user_id", userId).maybeSingle();
    if (readErr) return { content: [{ type: "text", text: readErr.message }], isError: true };
    if (!settings) {
      return { content: [{ type: "text", text: "Switch not configured. Set it up in the app first." }], isError: true };
    }
    const freq = settings.check_in_frequency || "30d";
    const match = /^(\d+)([dwm])$/.exec(freq);
    const next = new Date(now);
    if (match) {
      const n = parseInt(match[1], 10);
      const unit = match[2];
      if (unit === "d") next.setDate(next.getDate() + n);
      else if (unit === "w") next.setDate(next.getDate() + n * 7);
      else if (unit === "m") next.setMonth(next.getMonth() + n);
    } else {
      next.setDate(next.getDate() + 30);
    }
    const { error: updErr } = await supabase.from("user_settings").update({
      last_check_in: now.toISOString(),
      next_check_in_due: next.toISOString(),
      grace_period_active: false,
      grace_period_end: null,
      switch_triggered: false,
      switch_triggered_at: null
    }).eq("user_id", userId);
    if (updErr) return { content: [{ type: "text", text: updErr.message }], isError: true };
    await supabase.from("check_in_history").insert({
      user_id: userId,
      checked_in_at: now.toISOString(),
      deadline_at: next.toISOString(),
      deadline_mode: settings.deadline_mode ?? null,
      grace_period_hours: settings.grace_period_hours ?? null,
      method: "mcp"
    });
    return {
      content: [
        {
          type: "text",
          text: `Checked in. Next check-in due ${next.toISOString()}.`
        }
      ],
      structuredContent: { checked_in_at: now.toISOString(), next_check_in_due: next.toISOString() }
    };
  }
});

// src/lib/mcp/tools/get-plan.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_plan_default = defineTool3({
  name: "get_plan",
  title: "Get subscription plan",
  description: "Return the signed-in user's LegacyVault subscription plan (free, essential, or family) and expiry, if any.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("profiles").select("plan, plan_expires_at").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? { plan: "free" }) }],
      structuredContent: data ?? { plan: "free", plan_expires_at: null }
    };
  }
});

// src/lib/mcp/tools/list-contacts.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
function supabaseForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_contacts_default = defineTool4({
  name: "list_contacts_metadata",
  title: "List contacts (metadata only)",
  description: "List the signed-in user's trusted contacts by type, priority order, and email. LegacyVault uses zero-knowledge encryption, so contact names, phone numbers, and notes are encrypted client-side and are NOT returned by this tool.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser4(ctx).from("contacts").select("id, contact_type, email, priority_order, use_type_defaults, can_receive_messages, created_at").order("priority_order", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, contacts: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-check-in-history.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.58.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
function supabaseForUser5(ctx) {
  return createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_check_in_history_default = defineTool5({
  name: "get_check_in_history",
  title: "Get check-in history",
  description: "Return the signed-in user's recent check-in history entries, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).optional().describe("Max entries to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser5(ctx).from("check_in_history").select("checked_in_at, method, deadline_at, deadline_mode, grace_period_hours").order("checked_in_at", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { count: data?.length ?? 0, entries: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "aukkdhzrjglgiygsrrkz";
var mcp_default = defineMcp({
  name: "legacyvault-mcp",
  title: "LegacyVault",
  version: "0.1.0",
  instructions: "Tools for LegacyVault \u2014 a zero-knowledge encrypted dead man's switch. Use `perform_check_in` when the user says they are still alive/well or wants to reset the switch. Use `get_switch_status` to see when the next check-in is due. Encrypted fields (names, phone numbers, notes) are never returned; only metadata.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_switch_status_default, perform_check_in_default, get_plan_default, list_contacts_default, get_check_in_history_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
