// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ovdiwktpbmgjzqmatryi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im92ZGl3a3RwYm1nanpxbWF0cnlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MzEyMzIsImV4cCI6MjA2NDEwNzIzMn0.TehltzK_3YJxQ72-RyJVjo_MY72cU01N98at9iDq-aY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);